version: "2"

services:
  master:
    restart: unless-stopped
    image: blacktop/elasticsearch
    command: master
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  client:
    restart: unless-stopped
    image: blacktop/elasticsearch:kopf
    command: client
    ports:
      - "9200:9200"
    links:
     - master:elastic-master
    networks:
      - elastic
  data:
    restart: unless-stopped
    image: blacktop/elasticsearch
    environment:
      - ES_HEAP_SIZE=2g
    command: data
    links:
     - master:elastic-master
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    links:
     - client:elasticsearch
    networks:
      - elastic

volumes:
  data:

networks:
  elastic:
    driver: bridge
