version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache jq wget
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            cd $(cat LATEST)
            docker version
            docker build --cache-from=app -t app .
      - run:
          name: Get Docker image size
          command: |
            mkdir /tmp/artifacts;
            docker images --format "{{.Size}}" app > /tmp/artifacts/size;
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Download wait-for-es
          command: |
            wget https://github.com/blacktop/wait-for-es/releases/download/0.1.1/wait-for-es_0.1.1_Linux_x86_64.tar.gz
            tar xzf wait-for-es_0.1.1_Linux_x86_64.tar.gz
            ls -lah
      - run:
          name: Run elasticsearch
          command: |
            set -x
            docker run -d --name es -p 9200:9200 -e cluster.name=testcluster -e discovery.type=single-node app
            ./wait-for-es
            docker logs es
      - run:
          name: Run test
          command: |
            set -x
            docker run --rm --network container:es blacktop/httpie GET http://localhost:9200
