name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        latest: ${{ $(cat LATEST) }}
      run: |
        cd ${LATEST}; docker build . --file Dockerfile --tag blacktop/elasticsearch:${LATEST}