name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get LATEST version
      id: latest
      uses: blacktop/get-latest-version-action@master
    - name: Echo version
      run: echo 'Latest version is ${{ steps.latest.outputs.latest }}.'
    - name: Build the Docker image
      run: |
        cd ${{ steps.latest.outputs.latest }}
        docker build . --file Dockerfile --tag blacktop/elasticsearch:${{ steps.latest.outputs.latest }}