name: Docker Image CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd $(cat LATEST); docker build . --file Dockerfile --tag blacktop/elasticsearch:$(cat LATEST)
